# \u4E3Ariskproduct\u63D0\u4F9B\u4EE3\u7801\u751F\u6210\u529F\u80FD
# \u6A21\u677F\u914D\u7F6Ejson\u6620\u5C04\u6587\u4EF6
template.json.file=template-riskproduct.json
# \u672C\u5730\u8DEF\u5F84\u7684xml\u914D\u7F6E\u6587\u4EF6
config.xml.absolute.path=D:/0001\u65B0\u4EE3\u7801\u8DEF\u5F84/riskproduct
# \u672C\u5730\u8DEF\u5F84\u7684sql\u6587\u4EF6
sql.absolute.path=D:/idea_workspace/study-study/output-toolkit/output-toolkit-codegenerator/src/main/resources/create-sql.sql
# \u6A21\u677F\u6587\u4EF6\u7684\u524D\u7F00\u540D\u5B57
ftl.prefix.name=riskproduct
# dto\u6587\u4EF6\u7684\u5305\u540D
dto.packageName=com.bestpay.riskcontrol.riskproduct.api.entity

# vo\u6587\u4EF6\u7684\u5305\u540D
vo.packageName=com.bestpay.riskcontrol.riskproduct.aut.entity.vo
# mapper\u6587\u4EF6\u7684\u5305\u540D
mapper.packageName=com.bestpay.riskcontrol.riskproduct.aut.dal.mapper
# manager\u6587\u4EF6\u7684\u5305\u540D
manager.packageName=com.bestpay.riskcontrol.riskproduct.aut.manager
# controller\u6587\u4EF6\u7684\u5305\u540D
controller.packageName=com.bestpay.riskcontrol.riskproduct.aut.controller

# dto \u7684\u540E\u7F00\uFF0C\u9ED8\u8BA4\u4E3A DTO
dto.suffix=DTO
# mapper\u7684\u540E\u7F00\uFF0C\u5982Mapper\u8FD8\u662FDao\u7B49
mapper.suffix=Mapper
# manager\u7684\u540E\u7F00\uFF0C\u5982Manager\u8FD8\u662FService\u7B49
manager.suffix=Manager