server.port=8223
server.servlet.context-path=/outputtoolkit/codegen/


spring.profiles.active=riskproduct
spring.application.name=output-toolkit-codegenerator
spring.banner.charset=UTF-8


spring.freemarker.request-context-attribute=request
spring.freemarker.suffix=.html
spring.freemarker.content-type=text/html
spring.freemarker.enabled=true
spring.freemarker.cache=false
spring.freemarker.charset=UTF-8
spring.freemarker.allow-request-override=false
spring.freemarker.expose-request-attributes=true
spring.freemarker.expose-session-attributes=true
spring.freemarker.expose-spring-macro-helpers=true
spring.freemarker.settings.number_format=0.##
spring.freemarker.settings.default_encoding=UTF-8



OEM.version=
OEM.header=
OEM.keywords=
OEM.title=
OEM.slogan=
OEM.description=
OEM.author=zhouchuanxiang
OEM.packageName=
OEM.copyright=
OEM.returnUtilSuccess=
OEM.returnUtilFailure=ResponseUtil.error
OEM.outputStr=
OEM.mode=local