# 为riskproduct提供代码生成功能
# 模板配置json映射文件
template.json.file=template-riskproduct.json
# 本地路径的xml配置文件
config.xml.absolute.path=E:\\CODE_GENE\\riskproduct
# 本地路径的sql文件
sql.absolute.path=E:\\my_idea_workspace\\output-toolkit\\output-toolkit-codegenerator\\src\\main\\resources\\create-sql.sql
# 模板文件的前缀名字
ftl.prefix.name=riskproduct
# dto文件的包名
dto.packageName=com.bestpay.riskcontrol.riskproduct.api.entity

# vo文件的包名
vo.packageName=com.bestpay.riskcontrol.riskproduct.aut.entity.vo
# mapper文件的包名
mapper.packageName=com.bestpay.riskcontrol.riskproduct.aut.dal.mapper
# manager文件的包名
manager.packageName=com.bestpay.riskcontrol.riskproduct.aut.manager
# controller文件的包名
controller.packageName=com.bestpay.riskcontrol.riskproduct.aut.controller

# dto 的后缀，默认为 DTO
dto.suffix=DTO
# mapper的后缀，如Mapper还是Dao等
mapper.suffix=Mapper
# manager的后缀，如Manager还是Service等
manager.suffix=Manager