CREATE TABLE `r_cb_cm_base` (
                                `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                `item` varchar(16) DEFAULT NULL COMMENT '码表属性',
                                `cm_code` varchar(128) DEFAULT NULL COMMENT '码表编码',
                                `cm_name` varchar(2048) DEFAULT NULL COMMENT '码表名称',
                                `content` varchar(60000) DEFAULT NULL COMMENT '码表内容',
                                `cont_desc` varchar(256) DEFAULT NULL COMMENT '码表描述',
                                `load_env` varchar(32) DEFAULT NULL COMMENT '加载环境',
                                `load_system` varchar(2048) DEFAULT NULL COMMENT '加载系统',
                                `target` varchar(16) DEFAULT NULL COMMENT '目标源',
                                `action` varchar(16) DEFAULT NULL COMMENT '动作',
                                `expried` varchar(32) DEFAULT NULL COMMENT '数据的有效期',
                                `status` varchar(4) DEFAULT NULL COMMENT '状态0-待审核 2-已审核 4审核失败 1-生效中',
                                `release_status` varchar(4) DEFAULT NULL COMMENT '补录 0-未补录 1-已补录',
                                `created_at` datetime DEFAULT NULL COMMENT '创建时间',
                                `created_by` varchar(128) DEFAULT NULL COMMENT '创建人',
                                `updated_at` datetime DEFAULT NULL COMMENT '修改时间',
                                `updated_by` varchar(128) DEFAULT NULL COMMENT '修改人',
                                `audited_by` varchar(128) DEFAULT NULL COMMENT '审核人',
                                `audited_at` datetime DEFAULT NULL COMMENT '审核时间',
                                `remark` varchar(2048) DEFAULT NULL COMMENT '备注',
                                `version` varchar(50) DEFAULT NULL COMMENT '版本号',
                                PRIMARY KEY (`id`),
                                KEY `idx_cm_code` (`cm_code`) BLOCK_SIZE 16384 LOCAL
) AUTO_INCREMENT = 3003323 AUTO_INCREMENT_MODE = 'ORDER' DEFAULT CHARSET = utf8mb4 ROW_FORMAT = DYNAMIC COMPRESSION = 'zstd_1.3.8' REPLICA_NUM = 3 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0 COMMENT = '基础码表';