CREATE TABLE `t_p_auth_user_del` (
                                     `ID` varchar(32) NOT NULL COMMENT '主键',
                                     `STATUS` varchar(1) DEFAULT '1' COMMENT '0-无效 1-有效 2-冻结 3-锁定',
                                     `USER_NAME` varchar(128) NOT NULL COMMENT '用户登录名',
                                     `PASSWORD` varchar(128) DEFAULT NULL COMMENT '登录密码',
                                     `REAL_NAME` varchar(128) NOT NULL COMMENT '真实姓名',
                                     `NICK_NAME` varchar(128) DEFAULT NULL COMMENT '昵称',
                                     `SEX` varchar(1) DEFAULT NULL COMMENT '性别，F-女，M-男',
                                     `EMAIL` varchar(128) DEFAULT NULL COMMENT '电子邮箱',
                                     `MOBILE` varchar(256) DEFAULT NULL COMMENT '手机号',
                                     `PHONE` varchar(32) DEFAULT NULL COMMENT '固定电话',
                                     `RESIGN_DATE` datetime DEFAULT NULL COMMENT '离职时间',
                                     `DESCRIPTION` varchar(128) DEFAULT NULL COMMENT '描述',
                                     `PROVINCE` varchar(32) DEFAULT NULL COMMENT '省份',
                                     `CITY` varchar(32) DEFAULT NULL COMMENT '城市',
                                     `TYPE` varchar(1) DEFAULT '3' COMMENT '用户等级：1、超管，2、一级管理员，3、普通',
                                     `IS_RESIGN` varchar(1) DEFAULT '1' COMMENT '是否在职，1在职 0离职',
                                     `ORG_ID` varchar(32) DEFAULT NULL COMMENT '部门id',
                                     `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                     `CREATED_BY` varchar(128) NOT NULL DEFAULT 'SYS' COMMENT '创建人',
                                     `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
                                     `UPDATED_BY` varchar(128) NOT NULL DEFAULT 'SYS' COMMENT '修改人',
                                     `USER_ROLE_TYPE` varchar(2) DEFAULT NULL COMMENT '管理员,招标方与投标方区分标识 0管和1招标 2投标',
                                     `ACCOUNT_TYPE` varchar(2) DEFAULT NULL COMMENT '账号类型，01测试账号 02正式账号',
                                     `ENT_PERSON_TYPE` varchar(5) DEFAULT NULL COMMENT '人员类型：1：企业法人；2：企业代理人；为空时表示未认证',
                                     `CHANNEL` varchar(1) DEFAULT NULL COMMENT '是否三力渠道 1：是',
                                     PRIMARY KEY (`ID`)
)  COMMENT = '用户删除表';